### PR TITLE
PR Future GA test 20210709

### PR DESCRIPTION
**Pull request by aeiouaeiouaeiouaeiouaeiouaeiou**

### CODE REVIEW

**Comment by RJVB** [comment]
>  * [WFX] Use system clang when building on macOS.

What system do you do builds on? I'm not aware of any advantage of the system clang over builds of undoubtedly more recent versions that you can get from MacPorts or HB (other than the fact you already have it, of course).

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@RJVB I'm just testing of adding support for continuous integration via GitHub Actions for pull requests, a future branch unfortunately does not support systems older than 10.12.

**Comment by RJVB** [comment]
>@RJVB I'm just testing of adding support for continuous integration via GitHub Actions for pull requests, a future branch unfortunately does not support systems older than 10.12.

I know that, sadly, FF 78 is the last major version to target 10.9 . Already it seems impossible to play back DRM content in Waterfox (it remains blocked on the "activating components" status, presumably meaning it downloaded a widevine plugin that is too new for the OS).

**Comment by RJVB** [comment]
> a future branch unfortunately does not support systems older than 10.12.

FWIW, and since I don't see a way to file issue tickets:

Waterfox allows or requests a newer gmp-widevinegmp plugin (4.10.2209.1) than Firefox esr 78 (4.10.1582.2), one which doesn't work on 10.9 (it requires 10.11 as far as I've seen). I've been able to restore the directory of that older version and point the browser to it via about:config, but maybe you might want to check the code to clamp the max. version on 10.9 and 10.10 in your next release?

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@RJVB Apparently Widevine can work if you try to install the dummy libraries as described [in these instructions](https://github.com/blueboxd/chromium-legacy/wiki/DRM).

**Pull request merged**
